//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


[DataContract]
 public partial class ct_Limit
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ct_Limit()
    {
        this.ct_LGRel = new HashSet<ct_LGRel>();
        this.ct_LimtDetail = new HashSet<ct_LimtDetail>();
        this.ct_LRRel = new HashSet<ct_LRRel>();
        this.ct_ULRel = new HashSet<ct_ULRel>();
    }

    [DataMember]
	 public int ID { get; set; }
    [DataMember]
	 public int CU { get; set; }
    [DataMember]
	 public System.DateTime CT { get; set; }
    [DataMember]
	 public int LU { get; set; }
    [DataMember]
	 public System.DateTime LT { get; set; }
    [DataMember]
	 public Nullable<int> ST { get; set; }
    [DataMember]
	 public Nullable<int> GroupID { get; set; }
    [DataMember]
	 public Nullable<int> RoleID { get; set; }
    [DataMember]
	 public Nullable<int> UsersID { get; set; }
    [DataMember]
	 public string Common { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ct_LGRel> ct_LGRel { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ct_LimtDetail> ct_LimtDetail { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ct_LRRel> ct_LRRel { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ct_ULRel> ct_ULRel { get; set; }
}
