//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


[DataContract]
 public partial class ct_Users
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ct_Users()
    {
        this.ct_UGRel = new HashSet<ct_UGRel>();
        this.ct_ULRel = new HashSet<ct_ULRel>();
        this.ct_URRel = new HashSet<ct_URRel>();
    }

    [DataMember]
	 public int ID { get; set; }
    [DataMember]
	 public int CU { get; set; }
    [DataMember]
	 public System.DateTime CT { get; set; }
    [DataMember]
	 public int LU { get; set; }
    [DataMember]
	 public System.DateTime LT { get; set; }
    [DataMember]
	 public Nullable<int> ST { get; set; }
    [DataMember]
	 public string username { get; set; }
    [DataMember]
	 public string mobilephone { get; set; }
    [DataMember]
	 public string email { get; set; }
    [DataMember]
	 public string password { get; set; }
    [DataMember]
	 public string name { get; set; }
    [DataMember]
	 public string idno { get; set; }
    [DataMember]
	 public Nullable<int> gender { get; set; }
    [DataMember]
	 public string photo { get; set; }
    [DataMember]
	 public Nullable<int> CompanyID { get; set; }

    public virtual ct_Company ct_Company { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ct_UGRel> ct_UGRel { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ct_ULRel> ct_ULRel { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ct_URRel> ct_URRel { get; set; }
}
