//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


[DataContract]
 public partial class ht_admin_userrole
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ht_admin_userrole()
    {
        this.ht_userroleRel = new HashSet<ht_userroleRel>();
        this.Ht_Limit = new HashSet<Ht_Limit>();
        this.ht_CheckRoleRel = new HashSet<ht_CheckRoleRel>();
    }

    [DataMember]
	 public int ID { get; set; }
    [DataMember]
	 public Nullable<int> PID { get; set; }
    [DataMember]
	 public int CU { get; set; }
    [DataMember]
	 public System.DateTime CT { get; set; }
    [DataMember]
	 public int LU { get; set; }
    [DataMember]
	 public System.DateTime LT { get; set; }
    [DataMember]
	 public int ST { get; set; }
    [DataMember]
	 public string role_code { get; set; }
    [DataMember]
	 public string role_name { get; set; }
    [DataMember]
	 public string role_common { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ht_userroleRel> ht_userroleRel { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Ht_Limit> Ht_Limit { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ht_CheckRoleRel> ht_CheckRoleRel { get; set; }
}
