//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


[DataContract]
 public partial class Ht_Menu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ht_Menu()
    {
        this.Ht_LimitDetails = new HashSet<Ht_LimitDetails>();
    }

    [DataMember]
	 public int ID { get; set; }
    [DataMember]
	 public Nullable<int> PID { get; set; }
    [DataMember]
	 public int CU { get; set; }
    [DataMember]
	 public System.DateTime CT { get; set; }
    [DataMember]
	 public int LU { get; set; }
    [DataMember]
	 public System.DateTime LT { get; set; }
    [DataMember]
	 public int ST { get; set; }
    [DataMember]
	 public string Name { get; set; }
    [DataMember]
	 public Nullable<int> Floor { get; set; }
    [DataMember]
	 public Nullable<int> FloorID { get; set; }
    [DataMember]
	 public string Path { get; set; }
    [DataMember]
	 public string FloorName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Ht_LimitDetails> Ht_LimitDetails { get; set; }
}
