//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


[DataContract]
 public partial class ht_userroleRel
{
    [DataMember]
	 public int ID { get; set; }
    [DataMember]
	 public int CU { get; set; }
    [DataMember]
	 public System.DateTime CT { get; set; }
    [DataMember]
	 public int LU { get; set; }
    [DataMember]
	 public System.DateTime LT { get; set; }
    [DataMember]
	 public int ST { get; set; }
    [DataMember]
	 public int admin_id { get; set; }
    [DataMember]
	 public string admin_name { get; set; }
    [DataMember]
	 public int role_id { get; set; }
    [DataMember]
	 public string role_name { get; set; }

    public virtual ht_admin_user ht_admin_user { get; set; }
    public virtual ht_admin_userrole ht_admin_userrole { get; set; }
}
