//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


[DataContract]
 public partial class sysdiagrams
{
    [DataMember]
	 public string name { get; set; }
    [DataMember]
	 public int principal_id { get; set; }
    [DataMember]
	 public int diagram_id { get; set; }
    [DataMember]
	 public Nullable<int> version { get; set; }
    [DataMember]
	 public byte[] definition { get; set; }
}
