//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYMS.BSVIEW.MainService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.IMainService")]
    public interface IMainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/DoWork", ReplyAction="http://tempuri.org/IMainService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/DoWork", ReplyAction="http://tempuri.org/IMainService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/login", ReplyAction="http://tempuri.org/IMainService/loginResponse")]
        int login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/login", ReplyAction="http://tempuri.org/IMainService/loginResponse")]
        System.Threading.Tasks.Task<int> loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminUserAll", ReplyAction="http://tempuri.org/IMainService/AdminUserAllResponse")]
        string AdminUserAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminUserAll", ReplyAction="http://tempuri.org/IMainService/AdminUserAllResponse")]
        System.Threading.Tasks.Task<string> AdminUserAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/Add", ReplyAction="http://tempuri.org/IMainService/AddResponse")]
        string Add(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/Add", ReplyAction="http://tempuri.org/IMainService/AddResponse")]
        System.Threading.Tasks.Task<string> AddAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminByID", ReplyAction="http://tempuri.org/IMainService/AdminByIDResponse")]
        string AdminByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminByID", ReplyAction="http://tempuri.org/IMainService/AdminByIDResponse")]
        System.Threading.Tasks.Task<string> AdminByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/Update", ReplyAction="http://tempuri.org/IMainService/UpdateResponse")]
        string Update(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/Update", ReplyAction="http://tempuri.org/IMainService/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/Delete", ReplyAction="http://tempuri.org/IMainService/DeleteResponse")]
        string Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/Delete", ReplyAction="http://tempuri.org/IMainService/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleAll", ReplyAction="http://tempuri.org/IMainService/AdminRoleAllResponse")]
        string AdminRoleAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleAll", ReplyAction="http://tempuri.org/IMainService/AdminRoleAllResponse")]
        System.Threading.Tasks.Task<string> AdminRoleAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleAdd", ReplyAction="http://tempuri.org/IMainService/AdminRoleAddResponse")]
        string AdminRoleAdd(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleAdd", ReplyAction="http://tempuri.org/IMainService/AdminRoleAddResponse")]
        System.Threading.Tasks.Task<string> AdminRoleAddAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleByID", ReplyAction="http://tempuri.org/IMainService/AdminRoleByIDResponse")]
        string AdminRoleByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleByID", ReplyAction="http://tempuri.org/IMainService/AdminRoleByIDResponse")]
        System.Threading.Tasks.Task<string> AdminRoleByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleUpdate", ReplyAction="http://tempuri.org/IMainService/AdminRoleUpdateResponse")]
        string AdminRoleUpdate(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleUpdate", ReplyAction="http://tempuri.org/IMainService/AdminRoleUpdateResponse")]
        System.Threading.Tasks.Task<string> AdminRoleUpdateAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleDelete", ReplyAction="http://tempuri.org/IMainService/AdminRoleDeleteResponse")]
        string AdminRoleDelete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleDelete", ReplyAction="http://tempuri.org/IMainService/AdminRoleDeleteResponse")]
        System.Threading.Tasks.Task<string> AdminRoleDeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleRelAll", ReplyAction="http://tempuri.org/IMainService/AdminRoleRelAllResponse")]
        string AdminRoleRelAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleRelAll", ReplyAction="http://tempuri.org/IMainService/AdminRoleRelAllResponse")]
        System.Threading.Tasks.Task<string> AdminRoleRelAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleRelAdd", ReplyAction="http://tempuri.org/IMainService/AdminRoleRelAddResponse")]
        string AdminRoleRelAdd(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleRelAdd", ReplyAction="http://tempuri.org/IMainService/AdminRoleRelAddResponse")]
        System.Threading.Tasks.Task<string> AdminRoleRelAddAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleRelUpdate", ReplyAction="http://tempuri.org/IMainService/AdminRoleRelUpdateResponse")]
        string AdminRoleRelUpdate(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleRelUpdate", ReplyAction="http://tempuri.org/IMainService/AdminRoleRelUpdateResponse")]
        System.Threading.Tasks.Task<string> AdminRoleRelUpdateAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleRelEntity", ReplyAction="http://tempuri.org/IMainService/AdminRoleRelEntityResponse")]
        string AdminRoleRelEntity(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AdminRoleRelEntity", ReplyAction="http://tempuri.org/IMainService/AdminRoleRelEntityResponse")]
        System.Threading.Tasks.Task<string> AdminRoleRelEntityAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/RoleRelOpen", ReplyAction="http://tempuri.org/IMainService/RoleRelOpenResponse")]
        string RoleRelOpen(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/RoleRelOpen", ReplyAction="http://tempuri.org/IMainService/RoleRelOpenResponse")]
        System.Threading.Tasks.Task<string> RoleRelOpenAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuAll", ReplyAction="http://tempuri.org/IMainService/MenuAllResponse")]
        string MenuAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuAll", ReplyAction="http://tempuri.org/IMainService/MenuAllResponse")]
        System.Threading.Tasks.Task<string> MenuAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuAdd", ReplyAction="http://tempuri.org/IMainService/MenuAddResponse")]
        string MenuAdd(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuAdd", ReplyAction="http://tempuri.org/IMainService/MenuAddResponse")]
        System.Threading.Tasks.Task<string> MenuAddAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuUpdate", ReplyAction="http://tempuri.org/IMainService/MenuUpdateResponse")]
        string MenuUpdate(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuUpdate", ReplyAction="http://tempuri.org/IMainService/MenuUpdateResponse")]
        System.Threading.Tasks.Task<string> MenuUpdateAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuEntity", ReplyAction="http://tempuri.org/IMainService/MenuEntityResponse")]
        string MenuEntity(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuEntity", ReplyAction="http://tempuri.org/IMainService/MenuEntityResponse")]
        System.Threading.Tasks.Task<string> MenuEntityAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuOpen", ReplyAction="http://tempuri.org/IMainService/MenuOpenResponse")]
        string MenuOpen(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/MenuOpen", ReplyAction="http://tempuri.org/IMainService/MenuOpenResponse")]
        System.Threading.Tasks.Task<string> MenuOpenAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainServiceChannel : FYMS.BSVIEW.MainService.IMainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServiceClient : System.ServiceModel.ClientBase<FYMS.BSVIEW.MainService.IMainService>, FYMS.BSVIEW.MainService.IMainService {
        
        public MainServiceClient() {
        }
        
        public MainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public System.Threading.Tasks.Task<int> loginAsync(string username, string password) {
            return base.Channel.loginAsync(username, password);
        }
        
        public string AdminUserAll() {
            return base.Channel.AdminUserAll();
        }
        
        public System.Threading.Tasks.Task<string> AdminUserAllAsync() {
            return base.Channel.AdminUserAllAsync();
        }
        
        public string Add(string str) {
            return base.Channel.Add(str);
        }
        
        public System.Threading.Tasks.Task<string> AddAsync(string str) {
            return base.Channel.AddAsync(str);
        }
        
        public string AdminByID(int id) {
            return base.Channel.AdminByID(id);
        }
        
        public System.Threading.Tasks.Task<string> AdminByIDAsync(int id) {
            return base.Channel.AdminByIDAsync(id);
        }
        
        public string Update(string str) {
            return base.Channel.Update(str);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(string str) {
            return base.Channel.UpdateAsync(str);
        }
        
        public string Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public string AdminRoleAll() {
            return base.Channel.AdminRoleAll();
        }
        
        public System.Threading.Tasks.Task<string> AdminRoleAllAsync() {
            return base.Channel.AdminRoleAllAsync();
        }
        
        public string AdminRoleAdd(string str) {
            return base.Channel.AdminRoleAdd(str);
        }
        
        public System.Threading.Tasks.Task<string> AdminRoleAddAsync(string str) {
            return base.Channel.AdminRoleAddAsync(str);
        }
        
        public string AdminRoleByID(int id) {
            return base.Channel.AdminRoleByID(id);
        }
        
        public System.Threading.Tasks.Task<string> AdminRoleByIDAsync(int id) {
            return base.Channel.AdminRoleByIDAsync(id);
        }
        
        public string AdminRoleUpdate(string str) {
            return base.Channel.AdminRoleUpdate(str);
        }
        
        public System.Threading.Tasks.Task<string> AdminRoleUpdateAsync(string str) {
            return base.Channel.AdminRoleUpdateAsync(str);
        }
        
        public string AdminRoleDelete(int id) {
            return base.Channel.AdminRoleDelete(id);
        }
        
        public System.Threading.Tasks.Task<string> AdminRoleDeleteAsync(int id) {
            return base.Channel.AdminRoleDeleteAsync(id);
        }
        
        public string AdminRoleRelAll() {
            return base.Channel.AdminRoleRelAll();
        }
        
        public System.Threading.Tasks.Task<string> AdminRoleRelAllAsync() {
            return base.Channel.AdminRoleRelAllAsync();
        }
        
        public string AdminRoleRelAdd(string str) {
            return base.Channel.AdminRoleRelAdd(str);
        }
        
        public System.Threading.Tasks.Task<string> AdminRoleRelAddAsync(string str) {
            return base.Channel.AdminRoleRelAddAsync(str);
        }
        
        public string AdminRoleRelUpdate(string str) {
            return base.Channel.AdminRoleRelUpdate(str);
        }
        
        public System.Threading.Tasks.Task<string> AdminRoleRelUpdateAsync(string str) {
            return base.Channel.AdminRoleRelUpdateAsync(str);
        }
        
        public string AdminRoleRelEntity(int id) {
            return base.Channel.AdminRoleRelEntity(id);
        }
        
        public System.Threading.Tasks.Task<string> AdminRoleRelEntityAsync(int id) {
            return base.Channel.AdminRoleRelEntityAsync(id);
        }
        
        public string RoleRelOpen(int id) {
            return base.Channel.RoleRelOpen(id);
        }
        
        public System.Threading.Tasks.Task<string> RoleRelOpenAsync(int id) {
            return base.Channel.RoleRelOpenAsync(id);
        }
        
        public string MenuAll() {
            return base.Channel.MenuAll();
        }
        
        public System.Threading.Tasks.Task<string> MenuAllAsync() {
            return base.Channel.MenuAllAsync();
        }
        
        public string MenuAdd(string str) {
            return base.Channel.MenuAdd(str);
        }
        
        public System.Threading.Tasks.Task<string> MenuAddAsync(string str) {
            return base.Channel.MenuAddAsync(str);
        }
        
        public string MenuUpdate(string str) {
            return base.Channel.MenuUpdate(str);
        }
        
        public System.Threading.Tasks.Task<string> MenuUpdateAsync(string str) {
            return base.Channel.MenuUpdateAsync(str);
        }
        
        public string MenuEntity(int id) {
            return base.Channel.MenuEntity(id);
        }
        
        public System.Threading.Tasks.Task<string> MenuEntityAsync(int id) {
            return base.Channel.MenuEntityAsync(id);
        }
        
        public string MenuOpen(int id) {
            return base.Channel.MenuOpen(id);
        }
        
        public System.Threading.Tasks.Task<string> MenuOpenAsync(int id) {
            return base.Channel.MenuOpenAsync(id);
        }
    }
}
